% subjects = {'dlsub003',...
%             'dlsub099',...
%             'dlsub120',...
%             'dlsub123',...
%             'dlsub126',...
%             'dlsub127',...
%             'dlsub128',...
%             'dlsub131',...
%             'dlsub133',... 
%             'dlsub134',...
%             };
      
% for testing       
subjects = {'dlsub003'};        
        
SF_prfPropertiesCompare(subjects);